name: Run TradeAI_bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Esegue ogni 5 minuti
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install tvdatafeed manually
        run: pip install git+https://github.com/StreamAlpha/tvdatafeed.git
      
      - name: Run Python script
        run: python bot.py

      - name: Configura Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Aggiungi e sovrascrivi il file nel repository
        run: |
          git add candele.csv  # Sostituisci con il nome del tuo file
          git commit -m "Aggiornamento automatico del file" || echo "Nessuna modifica da salvare"
          git push origin main --force  # Sovrascrive il file precedente
